package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import ca.csf.mobile2.tp2.R
import ca.csf.mobile2.tp2.databinding.ActivityQuestionBinding
import org.androidannotations.annotations.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@DataBound
@EActivity(R.layout.activity_create_question)
class CreateQuestionActivity : AppCompatActivity(){

    //@Bean
    protected lateinit var questionService : CreateQuestionService

    protected fun onCreate(@BindingObject dataBinder : ActivityQuestionBinding){

    }

    @Click
    protected fun onPostButtonClick(){

    }
    //TODO:
}