package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import ca.csf.mobile2.tp2.R
import ca.csf.mobile2.tp2.databinding.ActivityQuestionBinding
import org.androidannotations.annotations.*
import java.util.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@DataBound
@EActivity(R.layout.activity_create_question)
class CreateQuestionActivity : AppCompatActivity(){

    @Bean
    protected lateinit var questionService : CreateQuestionService

    @InstanceState
    protected lateinit var viewModel:CreateQuestionActivityViewModel

    protected fun onCreate(@BindingObject dataBinder : ActivityQuestionBinding){

    }

    @Click(R.id.createQuestionButton)
    protected fun onPostButtonClick(){
        if(viewModel.questionText!="" && viewModel.choice1!="" && viewModel.choice2!=""){
            questionService.postQuestion(viewModel.createQuestion(),
                this::onQuestionPost,
                this::onConnectivityError,
                this::onServerError)
        }
    }
    @UiThread
    protected fun onQuestionPost(){

    }
    @UiThread
    protected fun onConnectivityError(){

    }
    @UiThread
    protected fun onServerError(){

    }
    //TODO:
}