package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.support.v7.app.AppCompatActivity
import ca.csf.mobile2.tp2.R
import ca.csf.mobile2.tp2.databinding.ActivityQuestionBinding
import org.androidannotations.annotations.Bean
import org.androidannotations.annotations.BindingObject
import org.androidannotations.annotations.DataBound
import org.androidannotations.annotations.EActivity

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@DataBound
@EActivity(R.layout.activity_question)
class CreateQuestionActivity : AppCompatActivity(){

    //@Bean
    //protected var lateinit questionService : CreateQuestionService

    protected fun onCreate(/*@BindingObject dataBinder : ActivityQuestionBinding*/){

    }
    //TODO:
}